name: Build And Test

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./csharp-cli
    
jobs:
  build:

    runs-on: ubuntu-latest

    services:
      test-db:
        image: mysql:8.0.26
        ports:
        - 13306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test tests --no-build --verbosity normal

